import type {
  Claim,
  FieldSummary,
  MaturityStage,
  ProgressType,
  SourceType,
  Technology,
  VerificationStatus,
} from "./types";

export const maturityStages: MaturityStage[] = [
  { level: 1, label: "Theory proposed", description: "A concept or model has been articulated." },
  { level: 2, label: "Lab signal", description: "Small-scale experimental evidence exists." },
  { level: 3, label: "Public paper", description: "The result is publicly documented." },
  { level: 4, label: "Independent reproduction", description: "A separate group has reproduced the claim." },
  { level: 5, label: "Prototype", description: "A working prototype has been demonstrated." },
  { level: 6, label: "Limited real use", description: "Early real-world usage is visible." },
  { level: 7, label: "Limited commercialization", description: "Commercial access exists but scale is constrained." },
  { level: 8, label: "Mass commercialization", description: "Broad market adoption is underway." },
  { level: 9, label: "Infrastructure", description: "The technology is embedded in society-scale systems." },
];

export const statusLabels: Record<VerificationStatus, string> = {
  unreviewed: "Unreviewed",
  "source-verified": "Source verified",
  "meaningful-progress": "Meaningful progress",
  limitations: "Limitations",
  "likely-overstated": "Likely overstated",
  "under-debate": "Under debate",
  rebutted: "Rebutted",
  "timeline-added": "Added to timeline",
  "maturity-updated": "Maturity updated",
};

export const sourceTypeLabels: Record<SourceType, string> = {
  paper: "Paper",
  preprint: "Preprint",
  "peer-reviewed-paper": "Peer-reviewed paper",
  "company-announcement": "Company announcement",
  "product-launch": "Product launch",
  patent: "Patent",
  "regulatory-document": "Regulatory document",
  "independent-test": "Independent test",
  benchmark: "Benchmark",
  "conference-talk": "Conference talk",
  "dataset-or-code": "Dataset or code",
  "press-coverage": "Press coverage",
};

export const progressTypeLabels: Record<ProgressType, string> = {
  performance: "Performance",
  cost: "Cost reduction",
  efficiency: "Efficiency",
  stability: "Stability",
  lifetime: "Lifetime",
  miniaturization: "Miniaturization",
  "manufacturing-scale": "Manufacturing scale",
  reproduction: "Reproduction",
  "product-deployment": "Product deployment",
  "regulatory-approval": "Regulatory approval",
  infrastructure: "Infrastructure",
  "new-method": "New method",
};

export const technologies: Technology[] = [
  {
    id: "solid-state-batteries",
    name: "Solid-state Batteries",
    category: "Batteries",
    field: "Energy storage",
    maturityLevel: 5,
    confidence: "Medium",
    summary: "High-density cells are moving from lab validation toward disputed pilot-line evidence.",
    currentAssessment:
      "Prototype performance is credible in narrow cell formats, but lifetime, interface resistance, yield, and cost remain the gating issues for broad commercialization.",
    recentChange: "Two pilot-production claims entered review; one open dataset was added to the timeline.",
    bottlenecks: ["Cycle life", "Interface resistance", "Yield", "Cost", "Thermal stability"],
    organizations: ["Northstar Cells", "Open Battery Consortium", "IonForge Materials"],
    timeline: [
      {
        id: "ssb-2021",
        year: "2021",
        title: "Lab-scale sulfide electrolyte stability improves",
        status: "source-verified",
        summary: "Multiple groups reported lower interface degradation in small cells.",
      },
      {
        id: "ssb-2023",
        year: "2023",
        title: "Pilot-line announcements accelerate",
        status: "under-debate",
        summary: "Several companies announced pilot manufacturing capacity without full yield data.",
      },
      {
        id: "ssb-2025",
        year: "2025",
        title: "Open cycle dataset reaches review queue",
        status: "timeline-added",
        summary: "A public dataset made cycle-life comparisons easier, but format differences remain.",
      },
    ],
  },
  {
    id: "lithium-metal-batteries",
    name: "Lithium-metal Batteries",
    category: "Batteries",
    field: "Cell chemistry",
    maturityLevel: 5,
    confidence: "Medium",
    summary: "High energy-density potential is clear, but dendrite control and lifetime remain limiting.",
    currentAssessment:
      "The chemistry has strong prototype evidence, but public data still varies widely by electrolyte, pressure, format, and cycle conditions.",
    recentChange: "Open cycle datasets improved comparability across small-format cells.",
    bottlenecks: ["Dendrite control", "Cycle life", "Pressure", "Electrolyte stability", "Scale-up"],
    organizations: ["Open Battery Consortium", "IonForge Materials", "Cell Metrics Lab"],
    timeline: [
      {
        id: "li-metal-2021",
        year: "2021",
        title: "Small-cell cycle data improves",
        status: "source-verified",
        summary: "Public papers showed better stability under narrow conditions.",
      },
      {
        id: "li-metal-2025",
        year: "2025",
        title: "Open datasets improve comparison",
        status: "timeline-added",
        summary: "Raw traces made it easier to separate strong evidence from claims.",
      },
    ],
  },
  {
    id: "sodium-ion-batteries",
    name: "Sodium-ion Batteries",
    category: "Batteries",
    field: "Grid and low-cost storage",
    maturityLevel: 7,
    confidence: "Medium",
    summary: "Commercialization is visible for lower-cost storage, though energy density remains lower.",
    currentAssessment:
      "The technology is entering limited commercialization where cost and material availability matter more than maximum energy density.",
    recentChange: "Factory announcements and early product deployments moved the category beyond lab-only evidence.",
    bottlenecks: ["Energy density", "Supply chain", "Long-term durability", "Product qualification", "Market fit"],
    organizations: ["GridCell", "LowCost Storage Group", "Sodium Energy Forum"],
    timeline: [
      {
        id: "sodium-2022",
        year: "2022",
        title: "Commercial cell announcements expand",
        status: "source-verified",
        summary: "Manufacturers began publishing more sodium-ion cell roadmaps.",
      },
      {
        id: "sodium-2025",
        year: "2025",
        title: "Limited product deployments appear",
        status: "meaningful-progress",
        summary: "Early deployments indicated real commercial interest in lower-cost storage.",
      },
    ],
  },
  {
    id: "multimodal-ai-agents",
    name: "Multimodal AI Agents",
    category: "Artificial Intelligence",
    field: "Agentic systems",
    maturityLevel: 6,
    confidence: "Medium",
    summary: "Agents can complete bounded digital workflows, but reliable autonomy is still task-specific.",
    currentAssessment:
      "The strongest evidence is in constrained tools, code tasks, and lab workflows. Long-horizon reliability, evaluation quality, and safety controls are still unresolved.",
    recentChange: "A lab-assistant demo was source verified but marked as limited by narrow task scope.",
    bottlenecks: ["Long-horizon reliability", "Evaluation design", "Tool safety", "Cost", "Auditability"],
    organizations: ["Helix AI", "CivicBench", "Open Lab Systems"],
    timeline: [
      {
        id: "agent-2023",
        year: "2023",
        title: "Tool-use benchmarks become common",
        status: "source-verified",
        summary: "Benchmarks started separating chat quality from tool execution.",
      },
      {
        id: "agent-2024",
        year: "2024",
        title: "Multi-step coding agents reach production trials",
        status: "meaningful-progress",
        summary: "Several teams reported practical use in constrained engineering workflows.",
      },
      {
        id: "agent-2026",
        year: "2026",
        title: "Lab-agent claims enter debate",
        status: "under-debate",
        summary: "Evidence suggests promise, but task selection and supervision level matter.",
      },
    ],
  },
  {
    id: "frontier-language-models",
    name: "Frontier Language Models",
    category: "Artificial Intelligence",
    field: "Foundation models",
    maturityLevel: 7,
    confidence: "High",
    summary: "Large language models are commercially deployed, but evaluation and reliability remain contested.",
    currentAssessment:
      "The category is commercially mature for assisted work, while autonomous reliability and domain-specific correctness still require careful review.",
    recentChange: "Deployment evidence is strong, but benchmark claims are often disputed.",
    bottlenecks: ["Reliability", "Evaluation leakage", "Cost", "Data provenance", "Safety controls"],
    organizations: ["Frontier Model Lab", "Open Evaluation Group", "Enterprise AI Bench"],
    timeline: [
      {
        id: "llm-2022",
        year: "2022",
        title: "General chat assistants reach mass use",
        status: "meaningful-progress",
        summary: "Public usage moved language models into broad commercial workflows.",
      },
      {
        id: "llm-2024",
        year: "2024",
        title: "Enterprise deployments expand",
        status: "source-verified",
        summary: "Evidence appeared across coding, support, writing, and internal search workflows.",
      },
      {
        id: "llm-2026",
        year: "2026",
        title: "Autonomous reliability remains debated",
        status: "under-debate",
        summary: "Long-horizon performance still depends heavily on task design and controls.",
      },
    ],
  },
  {
    id: "video-generation-models",
    name: "Video Generation Models",
    category: "Artificial Intelligence",
    field: "Generative media",
    maturityLevel: 6,
    confidence: "Medium",
    summary: "Short-form generation is usable, while controllability and production consistency remain uneven.",
    currentAssessment:
      "The technology is in limited real use for drafts and short assets, but long-form control, identity consistency, and licensing remain unresolved.",
    recentChange: "Several controlled editing demos entered review.",
    bottlenecks: ["Temporal consistency", "Editability", "Licensing", "Cost", "Long-form control"],
    organizations: ["FrameLab", "Open Video Eval", "Studio Systems Group"],
    timeline: [
      {
        id: "video-2023",
        year: "2023",
        title: "Short text-to-video demos improve",
        status: "source-verified",
        summary: "Public demos became more coherent for brief clips.",
      },
      {
        id: "video-2025",
        year: "2025",
        title: "Editing workflows appear",
        status: "meaningful-progress",
        summary: "Tools shifted from one-shot generation toward controlled iteration.",
      },
      {
        id: "video-2026",
        year: "2026",
        title: "Production consistency remains under debate",
        status: "under-debate",
        summary: "Claims vary widely by prompt control and post-production effort.",
      },
    ],
  },
  {
    id: "humanoid-robotics",
    name: "Humanoid Robotics",
    category: "Robotics",
    field: "Embodied automation",
    maturityLevel: 5,
    confidence: "Low",
    summary: "Warehouse and factory trials are visible, but uptime and unit economics are not settled.",
    currentAssessment:
      "Prototype demonstrations are improving quickly. Evidence for unsupervised, economically competitive deployment is still thin.",
    recentChange: "A warehouse shift-length trial is under debate due to unclear intervention rate.",
    bottlenecks: ["Dexterity", "Battery life", "Uptime", "Safety certification", "Unit economics"],
    organizations: ["Vector Robotics", "Foundry Motion", "Atlas Warehouse Lab"],
    timeline: [
      {
        id: "robot-2022",
        year: "2022",
        title: "General-purpose humanoid prototypes improve walking stability",
        status: "source-verified",
        summary: "Public demos showed better locomotion across controlled environments.",
      },
      {
        id: "robot-2024",
        year: "2024",
        title: "Factory pilots begin",
        status: "meaningful-progress",
        summary: "Limited industrial trials moved the category beyond lab demos.",
      },
      {
        id: "robot-2026",
        year: "2026",
        title: "Full-shift warehouse trial disputed",
        status: "under-debate",
        summary: "The claim lacks clear data on resets, teleoperation, and task mix.",
      },
    ],
  },
  {
    id: "robot-manipulation",
    name: "Robot Manipulation",
    category: "Robotics",
    field: "Dexterous control",
    maturityLevel: 6,
    confidence: "Medium",
    summary: "Constrained picking and assembly are in use, but general dexterity is still narrow.",
    currentAssessment:
      "Manipulation is commercially useful in structured settings, while flexible object handling remains a major research frontier.",
    recentChange: "Benchmark gains are visible, but real-world variation still limits transfer.",
    bottlenecks: ["Generalization", "Tactile feedback", "Object variation", "Safety", "Speed"],
    organizations: ["Foundry Motion", "Open Manipulation Bench", "Factory Robotics Lab"],
    timeline: [
      {
        id: "manip-2022",
        year: "2022",
        title: "Warehouse picking systems expand",
        status: "source-verified",
        summary: "Commercial deployments grew in constrained item-handling workflows.",
      },
      {
        id: "manip-2024",
        year: "2024",
        title: "Learning-based control improves",
        status: "meaningful-progress",
        summary: "Robots handled a wider range of objects in benchmarked trials.",
      },
      {
        id: "manip-2026",
        year: "2026",
        title: "General dexterity still unresolved",
        status: "limitations",
        summary: "Performance drops when objects, lighting, or work cells change.",
      },
    ],
  },
  {
    id: "autonomous-drones",
    name: "Autonomous Drones",
    category: "Robotics",
    field: "Mobile autonomy",
    maturityLevel: 7,
    confidence: "Medium",
    summary: "Commercial inspection and mapping are mature, while dense urban autonomy remains constrained.",
    currentAssessment:
      "Autonomous drones are commercially proven for bounded inspection, mapping, and monitoring, but broad city-scale autonomy faces regulation and safety constraints.",
    recentChange: "Regulated delivery pilots remain the main disputed frontier.",
    bottlenecks: ["Regulation", "Weather", "Dense airspace", "Battery life", "Safety certification"],
    organizations: ["SkyRoute", "Civil Airspace Lab", "Autonomous Inspection Group"],
    timeline: [
      {
        id: "drone-2021",
        year: "2021",
        title: "Inspection workflows scale",
        status: "source-verified",
        summary: "Industrial inspection and mapping saw broader commercial use.",
      },
      {
        id: "drone-2024",
        year: "2024",
        title: "Delivery pilots expand",
        status: "under-debate",
        summary: "Pilots increased, but economics and regulation remain mixed.",
      },
      {
        id: "drone-2026",
        year: "2026",
        title: "Urban autonomy remains constrained",
        status: "limitations",
        summary: "Safety case and airspace management still limit broad deployment.",
      },
    ],
  },
  {
    id: "fusion-pilot-plants",
    name: "Fusion Pilot Plants",
    category: "Fusion Energy",
    field: "Energy generation",
    maturityLevel: 4,
    confidence: "Low",
    summary: "Plasma milestones are public, but integrated net-electricity systems remain unproven.",
    currentAssessment:
      "The science signal has improved, but pilot-plant schedules still depend on materials, tritium supply, thermal conversion, and regulatory evidence that is not yet public.",
    recentChange: "An aggressive net-electricity schedule was flagged as likely overstated.",
    bottlenecks: ["Materials", "Tritium supply", "Thermal conversion", "Maintenance", "Regulatory path"],
    organizations: ["StellarGrid", "Public Fusion Lab", "Helion Materials Group"],
    timeline: [
      {
        id: "fusion-2022",
        year: "2022",
        title: "Ignition-class results raise confidence",
        status: "source-verified",
        summary: "Public experiments showed stronger plasma performance, but not grid electricity.",
      },
      {
        id: "fusion-2024",
        year: "2024",
        title: "Pilot-plant timelines accelerate",
        status: "under-debate",
        summary: "Company schedules moved faster than public subsystem evidence.",
      },
      {
        id: "fusion-2026",
        year: "2026",
        title: "Net-electricity schedule needs evidence",
        status: "likely-overstated",
        summary: "Reviewers flagged missing data on materials, fuel, and power conversion.",
      },
    ],
  },
  {
    id: "tritium-breeding",
    name: "Tritium Breeding",
    category: "Fusion Energy",
    field: "Fusion fuel cycle",
    maturityLevel: 3,
    confidence: "Low",
    summary: "Fuel-cycle evidence is still early compared with plasma-performance claims.",
    currentAssessment:
      "Public evidence remains mostly at the component and modeling level, making fuel supply one of the key blockers for reactor maturity.",
    recentChange: "Blanket concept papers remain short of integrated reproduction.",
    bottlenecks: ["Blanket materials", "Neutron flux", "Extraction", "Regulatory controls", "Inventory"],
    organizations: ["Public Fusion Lab", "Fuel Cycle Consortium", "Neutron Materials Group"],
    timeline: [
      {
        id: "tritium-2022",
        year: "2022",
        title: "Blanket concepts published",
        status: "source-verified",
        summary: "Several designs were documented, mostly through papers and simulations.",
      },
      {
        id: "tritium-2025",
        year: "2025",
        title: "Materials tests remain limited",
        status: "limitations",
        summary: "Integrated breeding and extraction evidence is not yet public.",
      },
    ],
  },
  {
    id: "fault-tolerant-quantum-computing",
    name: "Fault-tolerant Quantum Computing",
    category: "Quantum Computing",
    field: "Computing infrastructure",
    maturityLevel: 3,
    confidence: "Medium",
    summary: "Logical-qubit demonstrations are improving, but useful fault-tolerant workloads are not visible yet.",
    currentAssessment:
      "The field has public error-correction milestones, but comparisons are hard across hardware types and the path to useful workloads remains unsettled.",
    recentChange: "A logical-qubit milestone entered debate because hardware comparisons were unclear.",
    bottlenecks: ["Error correction overhead", "Qubit quality", "Control systems", "Useful algorithms", "Cooling"],
    organizations: ["QCore Systems", "Open Quantum Bench", "IonLogic Lab"],
    timeline: [
      {
        id: "quantum-2021",
        year: "2021",
        title: "Error-correction experiments become more reproducible",
        status: "source-verified",
        summary: "More groups reported stabilizer measurements and small-code demonstrations.",
      },
      {
        id: "quantum-2024",
        year: "2024",
        title: "Logical error rates improve",
        status: "meaningful-progress",
        summary: "Several papers showed lower logical error rates under constrained protocols.",
      },
      {
        id: "quantum-2026",
        year: "2026",
        title: "Useful-workload claims remain unproven",
        status: "under-debate",
        summary: "Reviewers need clearer comparisons from logical qubits to useful computation.",
      },
    ],
  },
  {
    id: "quantum-sensing",
    name: "Quantum Sensing",
    category: "Quantum Computing",
    field: "Measurement systems",
    maturityLevel: 6,
    confidence: "Medium",
    summary: "Narrow sensing applications are closer to deployment than general quantum computing.",
    currentAssessment:
      "The category has credible specialized use cases, but broad infrastructure adoption still depends on cost, calibration, and ruggedization.",
    recentChange: "Field-test evidence is stronger than most quantum-computing workload claims.",
    bottlenecks: ["Ruggedization", "Calibration", "Cost", "Integration", "Signal interpretation"],
    organizations: ["IonLogic Lab", "Precision Sensing Group", "GeoMeasure Systems"],
    timeline: [
      {
        id: "sensing-2022",
        year: "2022",
        title: "Field sensing demos increase",
        status: "source-verified",
        summary: "More devices moved from lab setups to controlled field trials.",
      },
      {
        id: "sensing-2025",
        year: "2025",
        title: "Specialized deployments appear",
        status: "meaningful-progress",
        summary: "Use cases in timing, navigation, and measurement became more visible.",
      },
    ],
  },
];

export const fields: FieldSummary[] = [
  {
    id: "artificial-intelligence",
    name: "Artificial Intelligence",
    description: "Models, agents, evaluation, deployment, and scientific discovery workflows.",
    recentChange: "Lab-assistant and coding-agent claims continue moving into review.",
    openDebate: "How much autonomy is real when supervision and retry budgets are counted?",
    maturityChange: "No maturity changes this week",
    technologyIds: ["multimodal-ai-agents", "frontier-language-models", "video-generation-models"],
  },
  {
    id: "batteries",
    name: "Batteries",
    description: "Cell chemistry, cycle life, energy density, manufacturing, and deployment.",
    recentChange: "Solid-state pilot-line evidence is now the highest-volume review topic.",
    openDebate: "Whether 500 Wh/kg cell claims include enough cycle-life context.",
    maturityChange: "One timeline addition pending",
    technologyIds: ["solid-state-batteries", "lithium-metal-batteries", "sodium-ion-batteries"],
  },
  {
    id: "robotics",
    name: "Robotics",
    description: "Humanoids, manipulation, autonomy stacks, industrial automation, and safety.",
    recentChange: "Full-shift humanoid trials are visible but intervention rates are unclear.",
    openDebate: "Whether demos are approaching economic deployment or still supervised pilots.",
    maturityChange: "No maturity changes this week",
    technologyIds: ["humanoid-robotics", "robot-manipulation", "autonomous-drones"],
  },
  {
    id: "fusion-energy",
    name: "Fusion Energy",
    description: "Confinement, ignition, reactor materials, tritium supply, and power conversion.",
    recentChange: "Net-electricity pilot schedules are being flagged as likely overstated.",
    openDebate: "Whether engineering schedules include materials and fuel constraints.",
    maturityChange: "No maturity changes this week",
    technologyIds: ["fusion-pilot-plants", "tritium-breeding"],
  },
  {
    id: "quantum-computing",
    name: "Quantum Computing",
    description: "Qubit quality, error correction, algorithms, control systems, and useful workloads.",
    recentChange: "Error-correction milestones need clearer comparisons across hardware types.",
    openDebate: "Whether logical-qubit demonstrations imply near-term useful computing.",
    maturityChange: "No maturity changes this week",
    technologyIds: ["fault-tolerant-quantum-computing", "quantum-sensing"],
  },
];

export const initialClaims: Claim[] = [
  {
    id: "claim-ssb-500whkg",
    title: "Northstar Cells reports a 500 Wh/kg sulfide solid-state pouch cell",
    technologyId: "solid-state-batteries",
    category: "Batteries",
    submittedBy: "mira",
    submittedAt: "2026-05-08",
    statuses: ["unreviewed", "limitations", "under-debate"],
    sourceTypes: ["company-announcement", "conference-talk"],
    progressTypes: ["performance", "manufacturing-scale"],
    summary:
      "The company claims a high-density pouch cell from a pilot line and says automotive samples are planned.",
    currentAssessment:
      "Potentially meaningful if the format and yield hold up, but the public material does not include cycle-life or production-yield data.",
    previousState: "Comparable public claims were mostly coin-cell or small-format demonstrations.",
    limitations: ["Cycle-life data is missing", "Pilot-line yield is not disclosed", "No independent reproduction"],
    sources: [
      {
        id: "source-ssb-1",
        title: "Prototype technical deck",
        publisher: "Northstar Cells",
        type: "company-announcement",
        url: "https://example.com/northstar-cells-deck",
      },
      {
        id: "source-ssb-2",
        title: "Battery Materials Forum presentation",
        publisher: "Battery Materials Forum",
        type: "conference-talk",
        url: "https://example.com/battery-forum-session",
      },
    ],
    rebuttals: ["The claim does not state whether the reported density includes packaging overhead."],
    communitySignals: {
      sourceHelpful: 18,
      needsVerification: 42,
      possibleDuplicate: 3,
      strongRebuttal: 11,
      timelineCandidate: 14,
      likelyOverstated: 21,
    },
  },
  {
    id: "claim-ssb-cycle-dataset",
    title: "Open Battery Consortium shares a 1,000-cycle lithium-metal cell dataset",
    technologyId: "solid-state-batteries",
    category: "Batteries",
    submittedBy: "joon",
    submittedAt: "2026-05-06",
    statuses: ["source-verified", "meaningful-progress", "timeline-added"],
    sourceTypes: ["dataset-or-code", "paper"],
    progressTypes: ["lifetime", "reproduction"],
    summary:
      "A public dataset adds comparable cycle-life traces for multiple electrolyte formulations.",
    currentAssessment:
      "Useful progress for verification because the raw curves and protocol notes are public, though the tested cells are still small.",
    previousState: "Most comparable data was locked inside papers or company summaries.",
    limitations: ["Small-format cells", "Limited temperature range", "No manufacturing cost data"],
    sources: [
      {
        id: "source-ssb-3",
        title: "Lithium-metal cycle dataset",
        publisher: "Open Battery Consortium",
        type: "dataset-or-code",
        url: "https://example.com/open-battery-dataset",
      },
      {
        id: "source-ssb-4",
        title: "Protocol note for solid electrolyte comparisons",
        publisher: "Open Battery Consortium",
        type: "paper",
        url: "https://example.com/protocol-note",
      },
    ],
    rebuttals: ["Dataset format differences still make direct comparison difficult."],
    communitySignals: {
      sourceHelpful: 57,
      needsVerification: 8,
      possibleDuplicate: 1,
      strongRebuttal: 4,
      timelineCandidate: 36,
      likelyOverstated: 2,
    },
  },
  {
    id: "claim-agent-lab-assistant",
    title: "Helix AI demonstrates a multimodal agent completing supervised lab workflows",
    technologyId: "multimodal-ai-agents",
    category: "Artificial Intelligence",
    submittedBy: "sana",
    submittedAt: "2026-05-05",
    statuses: ["source-verified", "limitations"],
    sourceTypes: ["company-announcement", "benchmark"],
    progressTypes: ["product-deployment", "performance"],
    summary:
      "The demo shows an agent reading experimental instructions, operating software tools, and generating a lab report under supervision.",
    currentAssessment:
      "The workflow evidence is relevant, but the task set is narrow and the supervision level is central to interpretation.",
    previousState: "Earlier demos were mostly screen-recorded tool use without workflow completion metrics.",
    limitations: ["Supervision is required", "Task selection is curated", "Failure cases are not public"],
    sources: [
      {
        id: "source-agent-1",
        title: "Lab assistant agent evaluation brief",
        publisher: "Helix AI",
        type: "company-announcement",
        url: "https://example.com/helix-agent-brief",
      },
      {
        id: "source-agent-2",
        title: "CivicBench lab workflow task set",
        publisher: "CivicBench",
        type: "benchmark",
        url: "https://example.com/civicbench-lab",
      },
    ],
    rebuttals: ["The published tasks may not represent messy real lab operations."],
    communitySignals: {
      sourceHelpful: 29,
      needsVerification: 24,
      possibleDuplicate: 2,
      strongRebuttal: 9,
      timelineCandidate: 19,
      likelyOverstated: 7,
    },
  },
  {
    id: "claim-humanoid-warehouse-shift",
    title: "Vector Robotics publishes an eight-hour warehouse humanoid trial",
    technologyId: "humanoid-robotics",
    category: "Robotics",
    submittedBy: "nora",
    submittedAt: "2026-05-04",
    statuses: ["under-debate", "limitations"],
    sourceTypes: ["company-announcement", "press-coverage"],
    progressTypes: ["product-deployment", "stability"],
    summary:
      "The company reports a full-shift trial for tote movement and shelf interaction in a controlled warehouse zone.",
    currentAssessment:
      "The duration is notable, but intervention rate, task mix, and safety constraints are not described enough for maturity updates.",
    previousState: "Public demonstrations were usually short, edited, or focused on one task.",
    limitations: ["Intervention rate unclear", "Teleoperation not ruled out", "Economic comparison missing"],
    sources: [
      {
        id: "source-robot-1",
        title: "Full-shift warehouse trial announcement",
        publisher: "Vector Robotics",
        type: "company-announcement",
        url: "https://example.com/vector-warehouse-trial",
      },
      {
        id: "source-robot-2",
        title: "Prototype robots enter warehouse pilots",
        publisher: "Industrial Automation Review",
        type: "press-coverage",
        url: "https://example.com/warehouse-pilots",
      },
    ],
    rebuttals: ["Trial footage does not show the full shift or all reset events."],
    communitySignals: {
      sourceHelpful: 16,
      needsVerification: 38,
      possibleDuplicate: 5,
      strongRebuttal: 18,
      timelineCandidate: 12,
      likelyOverstated: 20,
    },
  },
  {
    id: "claim-fusion-pilot-schedule",
    title: "StellarGrid announces a net-electricity pilot schedule",
    technologyId: "fusion-pilot-plants",
    category: "Fusion Energy",
    submittedBy: "kai",
    submittedAt: "2026-05-02",
    statuses: ["unreviewed", "likely-overstated"],
    sourceTypes: ["company-announcement"],
    progressTypes: ["infrastructure"],
    summary:
      "A fusion startup claims a pilot plant will send net electricity to the grid on an aggressive timeline.",
    currentAssessment:
      "The schedule is interesting but lacks public details on materials, tritium, thermal conversion, and regulatory milestones.",
    previousState: "Most public fusion progress remains around plasma performance and component prototypes.",
    limitations: ["Materials pathway unclear", "Fuel supply not addressed", "No regulator filings linked"],
    sources: [
      {
        id: "source-fusion-1",
        title: "Pilot plant schedule announcement",
        publisher: "StellarGrid",
        type: "company-announcement",
        url: "https://example.com/stellargrid-pilot",
      },
    ],
    rebuttals: ["Engineering milestones are stated as dates, not demonstrated subsystems."],
    communitySignals: {
      sourceHelpful: 8,
      needsVerification: 47,
      possibleDuplicate: 0,
      strongRebuttal: 19,
      timelineCandidate: 3,
      likelyOverstated: 41,
    },
  },
  {
    id: "claim-quantum-logical-qubit",
    title: "QCore Systems reports a logical-qubit error-correction milestone",
    technologyId: "fault-tolerant-quantum-computing",
    category: "Quantum Computing",
    submittedBy: "eli",
    submittedAt: "2026-05-01",
    statuses: ["source-verified", "under-debate"],
    sourceTypes: ["preprint", "benchmark"],
    progressTypes: ["performance", "new-method"],
    summary:
      "The team reports lower logical error rates on a small code and compares results against a public benchmark.",
    currentAssessment:
      "The result is relevant, but reviewers need a clearer bridge from the benchmark to useful fault-tolerant workloads.",
    previousState: "Earlier milestones focused on physical qubit quality or small demonstrations with limited comparability.",
    limitations: ["Small logical code", "No useful workload", "Hardware comparisons are difficult"],
    sources: [
      {
        id: "source-quantum-1",
        title: "Logical error reduction preprint",
        publisher: "QCore Systems",
        type: "preprint",
        url: "https://example.com/qcore-logical-error",
      },
      {
        id: "source-quantum-2",
        title: "Open Quantum Bench comparison table",
        publisher: "Open Quantum Bench",
        type: "benchmark",
        url: "https://example.com/open-quantum-bench",
      },
    ],
    rebuttals: ["The benchmark does not show end-to-end useful computation."],
    communitySignals: {
      sourceHelpful: 22,
      needsVerification: 19,
      possibleDuplicate: 1,
      strongRebuttal: 7,
      timelineCandidate: 13,
      likelyOverstated: 6,
    },
  },
];
